blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://hyper-chat.slack.com/archives/C023YLD15NZ
    about: If you can't get something to work the way you expect, open a question in
      the Hyper Slack support channel.
  - name: Feature Request
    url: https://hyper.io/slack
    about: Got an idea for a new feature in Hyper. Pop into Hyper slack and, share it with us.
  - name: ğŸ’¬ Hyper Slack
    url: https://hyper.io/slack
    about: Interact with other people using Hyper ğŸ’¿
  - name: ğŸ’¬ New Updates (Twitter)
    url: https://twitter.com/_hyper_io
    about: Stay up to date with Hyper news on twitter
  - name: ğŸ¿ Hyper YouTube Channel
    url: https://www.youtube.com/c/hypervideos
    about: Are you a tech lead or wanting to learn more about Hyper in depth? Checkout the Hyper YouTube Channel.
